baseURL  = "https://ndquan2110.github.io/"
languageCode = 'en-us'
title =  "Quan's Blog"
theme = 'ananke'
 
[menu]
	[[menu.main]]
		name = "Home"
		url = "/"
		weight = 1
	[[menu.main]]
		name = "Blog"
		url = "/posts/"
		weight = 2

[params]
	github = "https://github.com/ndquan2110/ndquan2110.github.io.git"
